-- European marketplace providers (AS24 ES/BE, AutoTrader.nl, Sauto, Automobile.it, Subito, Standvirtual, Mobile.bg).
INSERT INTO "providers" (
  "name",
  "internal_name",
  "type",
  "country",
  "base_url",
  "enabled",
  "rate_limit",
  "parser_version",
  "notes",
  "created_at",
  "updated_at"
)
VALUES
  (
    'AutoScout24 ES',
    'autoscout24_es',
    'classifieds',
    'ES',
    'https://www.autoscout24.es',
    true,
    20,
    'autoscout24_es-v1.0.0',
    'Spain AutoScout24. Next.js offers; VIN when labeled.',
    now(),
    now()
  ),
  (
    'AutoScout24 BE',
    'autoscout24_be',
    'classifieds',
    'BE',
    'https://www.autoscout24.be',
    true,
    20,
    'autoscout24_be-v1.0.0',
    'Belgium AutoScout24 (FR). Next.js offers; VIN when labeled.',
    now(),
    now()
  ),
  (
    'AutoTrader.nl',
    'autotradernl',
    'classifieds',
    'NL',
    'https://www.autotrader.nl',
    true,
    20,
    'autotradernl-v1.0.0',
    'Netherlands AutoTrader (AS24 family). Next.js offers; VIN when labeled.',
    now(),
    now()
  ),
  (
    'Sauto',
    'sauto',
    'classifieds',
    'CZ',
    'https://www.sauto.cz',
    true,
    25,
    'sauto-v1.0.0',
    'Czech Sauto.cz JSON API. VIN, mileage, photos, CZK prices.',
    now(),
    now()
  ),
  (
    'Automobile.it',
    'automobileit',
    'classifieds',
    'IT',
    'https://www.automobile.it',
    true,
    20,
    'automobileit-v1.0.0',
    'Italy Automobile.it. Next.js vehicleInformation; VIN from description.',
    now(),
    now()
  ),
  (
    'Subito',
    'subito',
    'classifieds',
    'IT',
    'https://www.subito.it',
    true,
    20,
    'subito-v1.0.0',
    'Italy Subito.it auto classifieds. Features from list; VIN from detail HTML.',
    now(),
    now()
  ),
  (
    'Standvirtual',
    'standvirtual',
    'classifieds',
    'PT',
    'https://www.standvirtual.com',
    true,
    20,
    'standvirtual-v1.0.0',
    'Portugal Standvirtual (OLX Cars). VIN from params/description.',
    now(),
    now()
  ),
  (
    'Mobile.bg',
    'mobilebg',
    'classifieds',
    'BG',
    'https://www.mobile.bg',
    true,
    20,
    'mobilebg-v1.0.0',
    'Bulgaria Mobile.bg. HTML VIN/Шаси labels, BGN/EUR price, gallery.',
    now(),
    now()
  )
ON CONFLICT ("internal_name") DO UPDATE SET
  "name" = EXCLUDED."name",
  "type" = EXCLUDED."type",
  "country" = EXCLUDED."country",
  "base_url" = EXCLUDED."base_url",
  "enabled" = EXCLUDED."enabled",
  "rate_limit" = EXCLUDED."rate_limit",
  "parser_version" = EXCLUDED."parser_version",
  "notes" = EXCLUDED."notes",
  "updated_at" = now();
